coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        
    patch:
      default:
        target: 30%
        
comment:
  layout: "reach,diff,flags,tree"
  behavior: default 
  require_changes: true
