name: Docker Image CI

on:
  push:
    branches: ["main", "action-docker-image"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file devops/Dockerfile --tag cta_backend_grupo_1:$(date +%s)
